import imgs from '~/assets/imgs';

const userData = [
    {
        id: 1,
        name: 'Trần Tuấn',
        password: '123456',
        level: 5,
        exp: 10000,
        totalNominate: 4,
        totalKeeps: 2,
        totalLike: 3,
        totalCmt: 3,
        avatar: imgs.avatarImg.user1,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 2,
        name: 'Trần Tùng',
        level: 1,
        exp: 0,
        totalNominate: 0,
        totalKeeps: 1,
        totalLike: 3,
        totalCmt: 4,
        avatar: imgs.avatarImg.user2,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 3,
        name: 'Trần Toàn',
        level: 2,
        exp: 50,
        totalNominate: 1,
        totalKeeps: 0,
        totalLike: 1,
        totalCmt: 1,
        avatar: imgs.avatarImg.user3,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 4,
        name: 'Trần Thắng',
        level: 4,
        exp: 5000,
        totalNominate: 0,
        totalKeeps: 5,
        totalLike: 1,
        totalCmt: 2,
        avatar: imgs.avatarImg.user4,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 5,
        name: 'Trần Tấn',
        level: 3,
        exp: 600,
        totalNominate: 0,
        totalKeeps: 1,
        totalLike: 0,
        totalCmt: 5,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 6,
        name: 'Trần Tú',
        level: 1,
        exp: 3,
        totalNominate: 5,
        totalKeeps: 1,
        totalLike: 4,
        totalCmt: 1,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 7,
        name: 'Nguyễn Hương',
        level: 3,
        exp: 150,
        totalNominate: 3,
        totalKeeps: 5,
        totalLike: 3,
        totalCmt: 0,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 8,
        name: 'Trần Thư',
        level: 1,
        exp: 2,
        totalNominate: 1,
        totalKeeps: 0,
        totalLike: 1,
        totalCmt: 0,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 9,
        name: 'Lê Quốc',
        level: 3,
        exp: 99,
        totalNominate: 2,
        totalKeeps: 0,
        totalLike: 5,
        totalCmt: 2,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 10,
        name: 'Nguyễn Quang',
        level: 1,
        exp: 5,
        totalNominate: 3,
        totalKeeps: 1,
        totalLike: 4,
        totalCmt: 6,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 11,
        name: 'Đặng Chính',
        level: 3,
        exp: 200,
        totalNominate: 4,
        totalKeeps: 4,
        totalLike: 1,
        totalCmt: 0,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
    {
        id: 12,
        name: 'Nguyễn Toản',
        level: 1,
        exp: 1,
        totalNominate: 6,
        totalKeeps: 3,
        totalLike: 0,
        totalCmt: 0,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
        createTime: '2020-10-11T10:32:48',
    },
];

export default userData;
