import imgs from '~/assets/imgs';

const userData = [
    {
        id: 1,
        name: 'Trần Tuấn',
        level: 5,
        avatar: imgs.avatarImg.user1,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 2,
        name: 'Trần Tùng',
        level: 1,
        avatar: imgs.avatarImg.user2,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 3,
        name: 'Trần Toàn',
        level: 2,
        avatar: imgs.avatarImg.user3,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 4,
        name: 'Trần Thắng',
        level: 4,
        avatar: imgs.avatarImg.user4,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 5,
        name: 'Trần Tấn',
        level: 3,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 6,
        name: 'Trần Tú',
        level: 1,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 7,
        name: 'Nguyễn Hương',
        level: 3,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 8,
        name: 'Trần Thư',
        level: 1,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 9,
        name: 'Lê Quốc',
        level: 3,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 10,
        name: 'Nguyễn Quang',
        level: 1,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 11,
        name: 'Đặng Chính',
        level: 3,
        avatar: imgs.avatarImg.user5,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
    {
        id: 12,
        name: 'Nguyễn Toản',
        level: 1,
        avatar: imgs.avatarImg.user6,
        sex: 'Nam',
        description: 'Yêu gia đình yêu cuộc sống',
        email: 'tuine03082000',
    },
];

export default userData;
